# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-23 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Textbooks', '0002_auto_20181023_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Edition',
            new_name='edition',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Publisher',
            new_name='publisher',
        ),
    ]
