# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-24 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textbooks', '0004_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wants',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
