# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-24 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textbooks', '0005_auto_20181024_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='0', max_length=13),
        ),
    ]
