# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textbooks', '0008_sells_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(default='https://goo.gl/7vbrVt', max_length=255),
        ),
    ]
