# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textbooks', '0012_auto_20181026_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='buyer_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
